export enum MessagePatternEnum {
  SEARCH_USERNAME = 'SEARCH_USERNAME',
  FIND_USER_INFO = 'FIND_USER_INFO',
  SIGNUP_USER = 'SIGNUP_USER',
  SIGNIN_USER = 'SIGNIN_USER',
  VALIDATE_TOKEN = 'VALIDATE_TOKEN',
  UPDATE_USER = 'UPDATE_USER'
}
